---
title: "useR! 2017 tutorial ideas"
output: html_document
# output: beamer_presentation
---


# Info

- 3 hours
- audience: R users
- 8 morning tutorials, 8 afternoon tutorial
- People who are fast in the practicals can check out https://www.openml.org/guide
- Bring post-its so people can show that they have a problem
- Create a little cheat sheet
- As preparation create a list of data sets not connected to a task
```{r, message=FALSE, eval=FALSE}
library("OpenML")

dat_info <- listOMLDataSets(limit = 99999)
tsk_info <- listOMLTasks(limit = 99999)

dat_has_task <- dat_info$data.id %in% tsk_info$data.id
dat_no_task <- which(!dat_has_task)
dat_info[dat_no_task, 1:6]
```

- Users should make an account in advance
- Users should install the R package



# Structure

## First slide
- If you haven't done so yet, create an account on OpenML.org
- If you haven't done so yet, install the OpenML R package and one of the packages farff or RWeka

## Intro to openml.org [15 minutes, Joaquin]
> Resources:  
> [NIPS slides](https://github.com/openml/articles/blob/master/OpenML%20NIPS.pdf)

- Why, what, how, who, for whom
- Data sets, tasks, flows, runs (all have their own website)
- vocabulary: features = covariates, number of observations = number of instances, ML = Machine Learing (not maximum likelihood)




## Intro to the OpenML R package
> Resources:  
> [Paper](https://bitbucket.org/giuseppec/openml-r-paper/src)  
> [Tutorial](http://openml.github.io/openml-r/vignettes/OpenML.html)  
> [Reisensburg talk](https://bitbucket.org/giuseppec/openml-r-paper/src)  
> [Heidi's departement presentation](https://github.com/openml/articles/tree/master/slides/heidi_hittisau)  
> [mlr loves OpenML blogpost](http://mlr-org.github.io/mlr-loves-OpenML/)



### Motivating example: A small benchmarking study demo [15 minutes, Bernd]

- How to run a simple benchmark study
- Link to batchmark blogpost



### Installation and configuration [3 minutes, Bernd]

----

*Practical* [5 minutes, Bernd]

- Install the OpenML R package (if you haven't done so yet)
- Add your API-key to your config file



### Listing [7 minutes, Bernd]

----

*Practical* [5 minutes, Bernd]

- List all regresssion tasks corresponding to data sets with between 
  50 and 55 observations.



### Downloading [10 minutes, Bernd]

----

*Practical* [5 minutes, Bernd]

- Download task with task ID XXX.


----

**BREAK**

----

### Intro to mlr [15 minutes, Bernd]
### Running and uploading [10 minutes, Bernd]

----

*Practical* [25 minutes, Bernd]

- Run your favorite learner/algorithm (from mlr) on task XXX that you already downloaded.
Hint: use `listLearners()` to find learners.
- Upload your run to OpenML. Add the tag "useR17". 
- Check if the upload worked by going to the website. Also check if the tag was
  added (you can also still add it on the website). 
- Check the website on how well you did
  

## Tagging and studies [10 minutes, Heidi]

----

*Practical* [10 minutes, Heidi]

- List the names of data sets in study_14 
- Summarize performance results 


## Short summary of the cool stuff we are already doing [15 minutes, Heidi]

## How to contribute [10 minutes, Heidi]

## Open Science is awesome, let's make it happen
