---
title: "OpenML"
author: |
  | Joaquin Vanschoren^1^ and Heidi Seibold^2^
  |
  | 1. Eindhoven University of Technology
  | 2. University of Zurich
institute:
- $^1$Department of Mathematics and Computer Science
- $^2$Epidemiology, Biostatistics and Prevention Institute
output: html_document
bibliography: openml_citations.bib
---

**Keywords**: Machine Learning, Online Platform, Collaboration, Open Science, Reproducible Research

[*OpenML*](http://www.openml.org/) [@Vanschoren2014openml] is an online
platform for collaborative and - as the name says - open machine learning.
Users can upload, organize, search and download data sets and corresponding
prediction tasks; they can run algorithms (flows) on the tasks and upload these
runs for everyone to see and compare to other solutions.  By connecting data,
tasks, flows and runs online, *OpenML* allows for easy and fast collaboration
to solve prediction challenges. 



# Aim of the tutorial
In this tutorial we want to introduce *R* users to the **OpenML** *R* package
[@Casalicchio2017openml] and show how everyone can easily contribute and make
use of *OpenML*. At the end of the tutorial we want every attendee to be able
to interact with the platform.

# Tutorial content
In this tutorial we want to give an introduction to the OpenML platform and the
*R* package. We want to work hands-on. The outline is as follows:

- Overview 
- Data, tasks, flows and runs
- Becoming a member
- *OpenML* as a social online platform
- **OpenML** and **mlr**
- The *R* package
    + Installation and configuration
    + Listing information
    + Downloading **OpenML** objects
    + Creating runs 
    + Uploading and Tagging
    + Further features
- Your first *OpenML* project


# Target audience and pre-requesites
The only pre-requesite you should have is a very basic understanding of *R*.
We aim to address a broad audience, since OpenML is interesting for all kinds
of people. OpenML is interesting for people who 

- have data (possibly with a prediction task they can't solve on their own), 
- analyse data, 
- develop algorithms, 
- want to learn about machine learning, or 
- teach machine learning.


# The instructors

[Joaquin Vanschoren](http://www.win.tue.nl/~jvanscho/) is the founder of OpenML
and professor of machine learing at the Eindhoven University of Technology.

[Heidi
Seibold](http://www.ebpi.uzh.ch/en/aboutus/departments/biostatistics/teambiostats/seibold.html)
is a PhD candidate in biostatistics at the University of Zurich.

*OpenML* is an open source community project. We gladly represent the amazing
[*OpenML* team](http://www.openml.org/guide#!team).


# OpenML at useR!
We believe that many useR! attendees will be interested in using *OpenML* for
their work, research and studies. The Open Source philosophy of *R* aligns with
OpenML. The form of a hands-on tutorial to introduce OpenML is perfect, since
the platform is only useful for people if they can actively participate. The
**OpenML** *R* package makes participation easy for *R* users and three hours
should get everyone into a state where they can use the package.

 <!-- - Goals/Aims/Learning objectives -->
 <!-- - Justification for running the tutorial at useR! 2017 -->
 <!-- - Description of the tutorial -->
 <!-- - Outline of the tutorial content -->
 <!-- - Pre-requisites -->
 <!-- - Potential attendees -->
 <!-- - Instructor biograph(y/ies) or link to online profile(s) -->
 <!-- - References -->
 


# References
